server:
  port: 8002

eureka:
  #eueka 主机名
  instance:
    hostname: localhost
  client:
    #提供者和消费者的注册地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka/

spring:
  application:
    name: demo-provider

#控制台彩色输出
  output:
    ansi:
      enabled: ALWAYS